baseURL = "https://icpcatucsd.github.io/"
languageCode = "en-us"
title = "Competitive Programming Club at UC San Diego"

[menu]
  [[menu.main]]
    identifier = "teams"
    name = "main-0"
    title = "Teams"
    url = "/teams/"
  [[menu.main]]
    identifier = "Meeting Schedule"
    name = "main-1"
    title = "Meeting Schedule"
    url = "/meeting-schedule/"
  [[menu.main]]
    identifier = "Team Selection"
    name = "main-2"
    title = "Team Selection"
    url = "/team-selection/"
  [[menu.main]]
    identifier = "Training Resources"
    name = "main-3"
    title = "Training Resources"
    url = "/resources/"
  [[menu.main]]
    identifier = "Contact"
    name = "main-4"
    title = "Contact Us"
    url = "/contact/"